name: AWS Federation Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::098906126589:role/GithubFederationRole
          aws-region: eu-central-1

      - run: aws sts get-caller-identity 